### PR TITLE
add to_not matcher

### PR DESCRIPTION
**Pull request by ashleygwilliams**
error messages need help but should be an exercise for another PR imo

### CODE REVIEW

**Comment by sgrif** [comment]
Thoughts on having a `NotMatcher` and the result being `to(not(whatever))` instead of `to_not(whatever)`?

**Comment by ashleygwilliams** [comment]
oh i could do that too, i just did what it seemed like @samphippen was suggesting i do

**Comment by fables-tales** [comment]
there's going to be a separate `not` matcher eventually, but separately the existence of a `to_not` is useful, so this seems good as is.

**Comment by ashleygwilliams** [comment]
@samphippen @sgrif shall i make a not matcher?

**Comment by fables-tales** [comment]
@ashleygwilliams if you want to, yeah!

**Comment by ashleygwilliams** [comment]
wrrd, i'll file an issue

**Pull request merged**
